### ISSUE TITLE
simulate spread on other types of networks

### ISSUE THREAD

**Issue by martinobelvederi** [csqsiew/spreadr#3]
Hello,
congratulations for the very nice package.  I'm relatively new to R, and can't code in C++
I'd like to use the package with psychological symptom networks. 
I noticed that when a node activation spreads to the others, the origin node loses activation, even if decay is 0 , or retention is 1.
I was wondering if it was possible to have an additional function where the "origin" node does not lose activation at each time point, but only propagates it to neighboring nodes (guess I should try and modify the "create_mat_t" c++ function, but I'm not able..
I realize this may not be useful for simulating spreading activation in linguistic networks
thanks in advance for your attention,
Martino

**Comment by ning-y** [comment]
Hi @martinobelvederi, thanks for your discussion! Could you clarify your desired behavior for:

> I noticed that when a node activation spreads to the others, the origin node loses activation, even if decay is 0 , or retention is 1.

Perhaps you can give an example. Here's the current behavior for zero decay, full retention in a simple digraph with one edge. The activation of node 1 does not spread to node 2.

```r
> network <- matrix(c(0, 1, 0, 0), nrow=2, byrow=TRUE)
> network
     [,1] [,2]
[1,]    0    1
[2,]    0    0
> start_run <- data.frame(node=1, activation=10)
> spreadr(network, start_run, decay=0, retention=1, time=2)
  node activation time
1    1         10    1
2    2          0    1
3    1         10    2
4    2          0    2
```

> I was wondering if it was possible to have an additional function where the "origin" node does not lose activation at each time point, but only propagates it to neighboring nodes

Is an origin node any node containing activation at any time point? Then retention should work.

**Comment by martinobelvederi** [comment]
Dear Ning,

thanks a lot for the reply.
Here's an example I'm working with
it's a weigthed net, based on symptoms. I understand that within the theory of spreading activation, if retention is full, there is no spread. When I select retention 0.9 there is some spread but the origin node loses activation.
What I'm looking for is a function that allows spread but does not entail a loss of activation from the origin node (sorry I can't explain myself better!)
in other words, if the three nodes start from 5 , they remain at 5 but activation propagates nonetheless to other nodes. If I select some level of decay, then the activation decays at a certain pace
thank you!!

# example

saveRDS(inet_hadscat, file = "inet_hadscat.rds")

result <-  spreadr(inet_hadscat, 
             data.frame(node=c("cough","phlegm", "chest_tight"),
             activation=c(5,5,5)),
             time=5, 
             include_t0=TRUE,
  retention=c(rep(1, 6), rep(1, 8)), 
  decay = c(rep(0, 6), rep(0, 8)))

ggplot(result, aes(x=time, y=activation, color=node)) +
  geom_point() +
  geom_line()
[inet_hadscat.xlsx](https://github.com/csqsiew/spreadr/files/7129110/inet_hadscat.xlsx)

**Comment by martinobelvederi** [comment]
ps I guess this would make activation rise continuously (virtually to infinite values if there are no negative edges) and I would need to set a limit of activation for each node

**Comment by ning-y** [comment]
I see what you mean! You can reproduce your desired behavior by adding activation to your initial node at each time point. If you add an amount of activation equal to the activation that spreads away from that node, it should look like what you're describing above (see the optional time column in the start_run data.frame).

Regarding adding this behavior as innate functionality: as far as I know, the package is not currently under active development, so it may be difficult for us to find time to implement this. I hope you're able to achieve your desired outcome with the method advice, though!

**Comment by martinobelvederi** [comment]
Dear Ning,
sorry I realize I didn't send the email
thank you very much again. I'll try working it out. I've noticed if I keep
activating a node at a certain level, the following time points the
activation increases above that level, consistent with the effect it is
receiving from other nodes.
Congratulations again on the nice package..
thanks Martino



Il giorno mer 8 set 2021 alle ore 19:39 ningOTI ***@***.***>
ha scritto:

**Comment by ning-y** [comment]
No worries, and feel free to comment again in this thread if you need help!
